//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_Assignment.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BlogComments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogComments()
        {
            this.ReplyBlogComments = new HashSet<ReplyBlogComments>();
        }

        [DisplayName("CommentID")]
        public int BlogCommentID { get; set; }
        [DisplayName("Full name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter fullname")]
        [StringLength(maximumLength: 50, MinimumLength = 5, ErrorMessage = "Fullname must be between 5 to 50")]
        public string FullName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter email")]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "Incorrect Email Format")]
        public string Email { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter phone")]
        [RegularExpression(@"\(?\d{3}\)?-? *\d{3}-? *-?\d{4}", ErrorMessage = "Incorrect Phone Number Format")]
        public string Phone { get; set; }
        [DisplayName("Content")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter content")]
        public string Comment { get; set; }
        public Nullable<System.DateTime> CommentingDate { get; set; }
        public Nullable<int> BlogID { get; set; }
    
        public virtual Blogs Blogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplyBlogComments> ReplyBlogComments { get; set; }
    }
}
