//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_Assignment.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Importation
    {
        public int ImportationID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Username { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please choose import date")]
        [DataType(DataType.DateTime, ErrorMessage = "Start date has been invalid")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm:ss}")]
        [DisplayName("Import date")]
        public Nullable<System.DateTime> ImportDate { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter unit price")]
        [DisplayName("Unit price")]
        [Range(maximum: Int64.MaxValue, minimum: 1, ErrorMessage = "Unit price must be a number")]
        public Nullable<int> UnitPrice { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter quantity")]
        [Range(maximum: Int64.MaxValue, minimum: 1, ErrorMessage = "Quantity must be a number")]
        public Nullable<int> Quantity { get; set; }

        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
