//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_Assignment.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ProductImage
    {
        public int ImgID { get; set; }
        [DisplayName("Image")]
        public string ImgFileName { get; set; }
        public Nullable<int> ProductID { get; set; }

        public virtual Products Products { get; set; }
    }
}